address = 0x53

# 本 sensor 有两种检测状态：活动检测 和 静止检测；
register_list = [
    [0x31,0x0B], # 禁止自测力； 设置默认为4线SPI； 中断高电平有效； 全分辨率模式； 数据右对齐； +- 16g 范围；
    [0x2C,0x08], # 关闭低功率模式（进入正常模式）；设置采样速率
    [0x2D,0x08], # 同时进行活动检测和静止检测；关闭自动休眠模式；关闭待机模式（进入测量模式）；关闭休眠模式（进入普通工作模式）；设置休眠模式下的唤醒频率为 8Hz
    [0x2E,0x80], # 仅使能 数据预备 中断（关闭其他中断）
    [0x1E,0x00], # 设置 OFSX 偏移调整（需要参考<偏移校准>中的比例因子）
    [0x1F,0x00], # 设置 OFSY 偏移调整（需要参考<偏移校准>中的比例因子）
    [0x20,0x05], # 设置 OFSZ 偏移调整（需要参考<偏移校准>中的比例因子）
]

