[init]
# disable write protect and switch bank
reg_list_1 = [
    [0x09, 0x5A],
    [0x3C, 0xAC],
    [0x09, 0xA5],
    [0x6D, 0x39],
]

# read chipid and verified here

# write configuration registers
reg_list_2 = [
    [0x19, 0x34],
    [0x3E, 0x73],
    [0x48, 0x2F],
    [0x1F, 0xFF],
    [0x73, 0x10],
    [0x69, 0x84],
    [0x68, 0x7F],
    [0x7D, 0x60],
    [0x60, 0x00],
    [0x6E, 0x17],
    [0x3F, 0x01],
    [0x52, 0x2E],
    [0x3F, 0x00],
    [0x59, 0x6A],
    [0x5A, 0x4E],
    [0x52, 0x70],
]

# check list below is used to check if the value in the registers was correct
check = [
    [0x19, 0x34],
    [0x3E, 0x73],
    [0x48, 0x2F],
    [0x1F, 0xBF],
    [0x73, 0x10],
    [0x69, 0x84],
    [0x68, 0x7F],
    [0x7D, 0x60],
    [0x60, 0x00],
    [0x6E, 0x17],
    [0x3F, 0x00],
    [0x59, 0x6A],
    [0x5A, 0x4E],
    [0x52, 0x70],
]