[electronic]
vdd_voltage = "1v8"

[init]
reg_list_1 = [
    [0x40,0x80],
    [0x55,0x01],
    [0x7f,0x0e],
    [0x43,0x1d],
]

# Read 0x46 and store in Var R1

reg_list_2 = [
    [0x43,0x1e],
]

# Read 0x46 and store in Var R2

reg_list_3 = [
    [0x7f,0x14],
]

# append [0x6A, R1] and [0x6C, R2] to reg_list_3

reg_list_4 = [
    [0x7f,0x00],
    [0x55,0x00],
    [0x4d,0xd0],
    [0x4e,0x23],
    [0x4f,0x46],
    [0x77,0x24],
    [0x7f,0x05],
    [0x44,0xa8],
    [0x4a,0x14],
    [0x53,0x0c],
    [0x5b,0xea],
    [0x61,0x13],
    [0x62,0x07],
    [0x64,0xd8],
    [0x6d,0x86],
    [0x7d,0x84],
    [0x7e,0x00],
    [0x7f,0x06],
    [0x60,0x70],
    [0x61,0x00],
    [0x7e,0x40],
    [0x7f,0x07],
    [0x42,0x16],
    [0x7f,0x09],
    [0x40,0x03],
    [0x7f,0x0a],
    [0x49,0x00],
    [0x4a,0x23],
    [0x4c,0x28],
    [0x4f,0x02],
    [0x7f,0x0c],
    [0x40,0xa0],
    [0x41,0x70],
    [0x42,0x20],
    [0x43,0xc5],
    [0x44,0x44],
    [0x45,0x04],
    [0x4c,0x60],
    [0x54,0x00],
    [0x55,0x40],
    [0x59,0x93],
    [0x7f,0x0d],
    [0x4f,0x02],
    [0x4e,0x6b],
    [0x7f,0x14],
    [0x4a,0x67],
    [0x62,0x1c],
    [0x63,0x1c],
    [0x6d,0x82],
    [0x6f,0xd8],
    [0x73,0x83],
    [0x74,0x00],
    [0x7a,0x16],
    [0x7f,0x10],
    [0x48,0x0f],
    [0x49,0x88],
    [0x4c,0x1d],
    [0x4f,0x08],
    [0x51,0x6f],
    [0x52,0x90],
    [0x54,0x64],
    [0x55,0xf0],
    [0x5c,0x40],
    [0x61,0xee],
    [0x62,0xe5],
    [0x7f,0x00],
    [0x5b,0x40],
    [0x61,0xad],
    [0x51,0xea],
    [0x19,0x9f],
]

# critical read 0x20 at 1ms interval until 0x0F is obtained of read up to 55ms

reg_list_5 = [
    [0x19, 0x00],
    [0x40, 0x00],
    [0x61, 0xD5],
    [0x7F, 0x00],
]

[mode_reg_list]
high_performance_mode = [
]

low_power_mode = [
]

office_mode = [
]

corded_gaming_mode = [
]
