address = 0x74
chipid = 0x585B
register_list = [
    # basic settings
    [0x09, 0x5A],
    [0x3C, 0xAC],
    [0x09, 0xA5],
    [0x6D, 0x39],
    [0x19, 0x04],
    [0x0D, 0x20, 0x20],
    # advanced settings
    [0x3E, 0x71],
    [0x48, 0xFF],
    [0x1F, 0xFF],
    [0x73, 0x10],
    [0x68, 0x7F, 0x84],
    [0x7D, 0x60],
    # [0x7E, 0x00],
    [0x60, 0x00],
    [0x6E, 0x37],
    [0x3F, 0x01],
    [0x52, 0x2E],
    [0x3F, 0x00],
    [0x0B, 0x70],
    [0x05, 0xBC],
]